### ISSUE TITLE
The make install command use an unexisting instruction

### ISSUE THREAD

**Issue by c4ilus** [bolt/project#109]
The make install command lauch a make db-create command that don't exists. 

The error message we get : 
```
make db-create
make[1]: Entering directory '/srv/bolt'
make[1]: *** No rule to make target 'db-create'.  Stop.
make[1]: Leaving directory '/srv/bolt'
make: *** [Makefile:9: install] Error 2
```

**Comment by bobdenotter** [comment]
Hi @c4ilus ,

Thanks for pointing this out.. I've made a slightly alternative fix in #111 

In a day or two, we'll package new releases with this fix in it.
