### ISSUE TITLE
Clone, up and got .sh error...

### ISSUE THREAD

**Issue by AndreyChursin** [bolt/project#121]
after run "docker-compose up -d" I've got error:
![image](https://user-images.githubusercontent.com/11028058/215082454-dd2a5e6b-797f-4fb2-b5c5-115b85516ffa.png)

Why? Why you build php container via .sh script which is not work correctly?!
And how I can fix it?

**Comment by bobdenotter** [comment]
> Why? Why you build php container via .sh script which is not work correctly?!

Because we're only human, and don't have infinite resources. My apologies.
