### ISSUE TITLE
Unavailable dependency `bobdenotter/commando`

### ISSUE THREAD

**Issue by jordanaubert** [bolt/project#124]
Hello, I'm trying to update the dependencies of the project but the package `bobdenotter/yaml-migrations:1.2.0` has a dependency on an unavailable package `bobdenotter/commando`. Downgrading to `bobdenotter/yaml-migrations:1.1.2` fix the problem for the moment.

Will `bobdenotter/commando` be up again ?

**Comment by bobdenotter** [comment]
Apologies! It's back online now!
