### ISSUE TITLE
Add Template Repository in Github ?

### ISSUE THREAD

**Issue by toofff** [bolt/project#29]
Why not use the template feature on your github repository for installing a new Bolt project?

Link that you could add directly to your website?

[Here is the official Github documentation](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/creating-a-template-repository)

**Comment by bobdenotter** [comment]
Hmm, interesting. I suppose it would be more of a feature for experienced developers. It'd be like "Here, fork this if you'd like, but you're on your own", because it doesn't automatically run these: 

```bash
composer run post-create-project-cmd
composer run post-install-cmd
```

I'll set up template right now, but we should probably document it somewhere, as well.

**Comment by toofff** [comment]
You can test on [API Platform](https://github.com/api-platform/api-platform), it's already in place. 

It is interesting for developers when they want to create a new github repository with the basis of a Bolt project with best practices and always up to date.. These are the little extras that developers like and don't take too long to set up: D

This is why I am working hard to finish my pull request as soon as possible to add a real Docker base with best practices and images that can be used in development and in production, but I still have work to do above.

**Comment by toofff** [comment]
Top :+1:, I close my issue ;)

![image](https://user-images.githubusercontent.com/966550/95424605-2bf70580-0943-11eb-843e-a6d40b6f424f.png)
