### ISSUE TITLE
Flaky external service causes problems during project setup.

### ISSUE THREAD

**Issue by ADmad** [bolt/project#34]
Running `bin/console bolt:setup` and choosing to `yes` for `Add fixtures (dummy content) to the Database? (yes/no)` I ended up with error

```
In ResponseTrait.php line 280:
                                                                                                                        
  HTTP/1.1 503 Service Unavailable returned for "https://source.unsplash.com/1280x1024/?portrait,face,headshot/23227".  
                                                                                                                        
```

The service seems down and that URL is inaccessible. I guess some better error handling or falling back to another service is required to mitigate this scenario.

**Comment by kiamlaluno** [comment]
I tried accessing https://source.unsplash.com/1280x1024/?portrait,face,headshot/23227 from the browser, and I can see the image.

**Comment by ADmad** [comment]
It is/was an intermittent issue and not about a specific URL.

**Comment by bobdenotter** [comment]
Fixed in the Bolt 5 beta's:

```
composer create-project bolt/project playground "^2.0" --stability=beta
```
