### ISSUE TITLE
"Your requirements could not be resolved to an installable set of packages" with php 8

### ISSUE THREAD

**Issue by adjaya-dev** [bolt/project#63]
`composer create-project bolt/project bolt

Creating a "bolt/project" project at "./bolt"
Installing bolt/project (1.3.19)
  - Downloading bolt/project (1.3.19)
  - Installing bolt/project (1.3.19): Extracting archive
Created project in /home/___/public_html/BOLT_1/bolt
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - bolt/common is locked to version 2.1.10 and an update of this package was not requested.
    - bolt/common 2.1.10 requires php ^7.1 -> your php version (8.0.1) does not satisfy that requirement.
  Problem 2
    - doctrine/dbal is locked to version 2.10.4 and an update of this package was not requested.
    - doctrine/dbal 2.10.4 requires php ^7.2 -> your php version (8.0.1) does not satisfy that requirement.
  Problem 3
    - php-translation/common is locked to version 3.0.1 and an update of this package was not requested.
    - php-translation/common 3.0.1 requires php ^7.2 -> your php version (8.0.1) does not satisfy that requirement.
  Problem 4
    - php-translation/extractor is locked to version 2.0.2 and an update of this package was not requested.
    - php-translation/extractor 2.0.2 requires php ^7.2 -> your php version (8.0.1) does not satisfy that requirement.
  Problem 5
    - php-translation/symfony-bundle is locked to version 0.12.1 and an update of this package was not requested.
    - php-translation/symfony-bundle 0.12.1 requires php ^7.1 -> your php version (8.0.1) does not satisfy that requirement.
  Problem 6
    - php-translation/symfony-storage is locked to version 2.2.0 and an update of this package was not requested.
    - php-translation/symfony-storage 2.2.0 requires php ^7.2 -> your php version (8.0.1) does not satisfy that requirement.
  Problem 7
    - phpdocumentor/reflection-docblock is locked to version 4.3.4 and an update of this package was not requested.
    - phpdocumentor/reflection-docblock 4.3.4 requires php ^7.0 -> your php version (8.0.1) does not satisfy that requirement.
  Problem 8
    - tightenco/collect is locked to version v7.26.1 and an update of this package was not requested.
    - tightenco/collect v7.26.1 requires php ^7.1.3 -> your php version (8.0.1) does not satisfy that requirement.
  Problem 9
    - doctrine/dbal 2.10.4 requires php ^7.2 -> your php version (8.0.1) does not satisfy that requirement.
    - knplabs/doctrine-behaviors v2.0.8 requires doctrine/dbal ^2.9 -> satisfiable by doctrine/dbal[2.10.4].
    - knplabs/doctrine-behaviors is locked to version v2.0.8 and an update of this package was not requested.`

`composer update
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - bolt/core[4.1.0, ..., 4.1.12] require php-translation/symfony-bundle ^0.12 -> satisfiable by php-translation/symfony-bundle[0.12, 0.12.1].
    - php-translation/symfony-bundle[0.12, ..., 0.12.1] require php ^7.1 -> your php version (8.0.1) does not satisfy that requirement.
    - Root composer.json requires bolt/core ^4.1 -> satisfiable by bolt/core[4.1.0, ..., 4.1.12].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.`

**Comment by toofff** [comment]
For the moment, the Bolt project is not upgraded to PHP version 8.

I don't know when it will be available for PHP 8. @bobdenotter Do you think you have a vision for a switchover date to PHP 8?

**Comment by bobdenotter** [comment]
```
composer create-project bolt/project playground "^2.0" --stability=beta
```

Should get you a working version of Bolt 5 beta, for PHP 8 now.
