### ISSUE TITLE
Mistake in composer.json in release 1.3.26

### ISSUE THREAD

**Issue by Darkikim** [bolt/project#67]
Hy,

The dependencies in the version 1.3.26 are the dependencies from bolt 5 and not bolt 4 

```json
"description": "Bolt 5 standard project skeleton",
    "license": "MIT",
    "require": {
        "bobdenotter/configuration-notices": "^1.0",
        "bobdenotter/weatherwidget": "^1.1",
        "bolt/article": "^1.0",
        "bolt/assets": "^5.0",
        "bolt/core": "^5.0",
        "bolt/newswidget": "^1.1",
        "bolt/redactor": "^1.0",
        "bolt/themes": "^3.3",
        "nelmio/security-bundle": "^2.10",
        "symfony/flex": "^1.6"
    },
```

Link to the [composer.json](https://github.com/bolt/project/blob/1.3.26/composer.json)

Maybe fix it could be a good option to let us install bolt 4 without having a bolt 5 beta project ^^

**Comment by Darkikim** [comment]
Temporary fix : 
`composer create-project bolt/project bolt "1.3.25"`

**Comment by bobdenotter** [comment]
Ugh, I'll look fix that. I probably released the wrong branch!

**Comment by bobdenotter** [comment]
Thanks for bringing this to my attention, @Darkikim 👍 

If you run `composer create-project bolt/project playground` now, you'll properly get Bolt 4.1 again. 

If you _want_ to get the beta for 5 on the other hand, you can run this: 

```
composer create-project bolt/project playground "^2.0" --stability=beta
```

**Comment by Darkikim** [comment]
Yep thanks for this quick reply and fix 😃
