### ISSUE TITLE
Composer update produces error: MetadataStorageError.php line 13

### ISSUE THREAD

**Issue by garrettboone** [bolt/project#93]
I installed Bolt via the project, and ran `composer update`.

Initial results:
```
Nothing to install, update or remove...
[OK] Cache for the "prod" environment (debug=false) was successfully cleared...
[OK] All assets were successfully installed...
[OK] All assets were successfully installed...
```

But then this error:
```
11:44:43 CRITICAL  [console] Error thrown while running command "doctrine:migrations:up-to-date --ansi". Message: "The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue." ["exception" => Doctrine\Migrations\Exception\MetadataStorageError^ { …},"command" => "doctrine:migrations:up-to-date --ansi","message" => "The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue."]

In MetadataStorageError.php line 13:

The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue.

doctrine:migrations:up-to-date [-u|--fail-on-unregistered] [-l|--list-migrations] [--configuration CONFIGURATION] [--em EM] [--conn CONN]


[WARNING] Please run `php bin/console doctrine:migrations:migrate` to execute the database migrations.

⚙️  Bolt
=======

 Bolt version: 5.0.0

 * Install type: Packaged distribution
 * Database: mysql 5.5.5-10.3.31-MariaDB-0ubuntu0.20.04.1 - Localhost via UNIX socket (with JSON)
 * PHP version: 7.4.3
 * Symfony version: v5.3.7
 * Operating System: Linux - 5.4.0-81-generic
```

I ran `bin/console doctrine:migrations:sync-metadata-storage` and it was ok. I also did `doctrine:migrations:migrate` but there were no migrations to run.

When I run `composer update` it shows same error again.

**Comment by bobdenotter** [comment]
🙈 

Run `bin/console doctrine:schema:update --force --complete` 

(i've never messed up a database using this, but it never hurts to make a backup, just in case)

**Comment by garrettboone** [comment]
Thanks, I ran `bin/console doctrine:schema:update --force --complete`.
Then I ran `composer update` again which reported 1 migration needed. 
I ran ` bin/console doctrine:migrations:migrate` which reported 1 migration completed.

After running `composer update` again, the original error is still showing. I repeated the steps above again but same result - is this to be expected?

**Comment by garrettboone** [comment]
Additional info:

```
MariaDB [db_name]> select * from doctrine_migration_versions;
+-----------------------------------------------+---------------------+----------------+
| version                                       | executed_at         | execution_time |
+-----------------------------------------------+---------------------+----------------+
| Bolt\DoctrineMigrations\Version20201210105836 | 2021-09-10 12:08:55 |            126 |
+-----------------------------------------------+---------------------+----------------+
1 row in set (0.000 sec)
```
There are also no migration files in the migrations folder.

**Comment by bobdenotter** [comment]
If you ignore the error, does Bolt otherwise work? 

> There are also no migration files in the migrations folder.

They're in `vendor/bolt/core/Migrations`

**Comment by garrettboone** [comment]
I figured it out - I had the serverVersion for the db in my .env set to `5.7` (I think because of the notes in the .env). Changing it to my version of `10.3.31-MariaDB-0ubuntu0.20.04.1` fixes this error. Also, removing the serverVersion parameter seems to work ok too.

Sorry for the hassle - and thanks for the help!
